version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    ports:
      - 3000:3000

  mongo-express:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-server
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    links:
      - db
    networks:
      - mongo-compose-network

  db:
    image: mongo:3.6.19-xenial
    container_name: mongo-server
    environment:
      MONGO_INITDB_DATABASE: devdb  
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container/data/db
    networks:
      - mongo-compose-network

networks: 
    mongo-compose-network:
      driver: bridge