version: '3.7'

services:
  app:
    build:
      context: .
    container_name: sciapi_api
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    ports:
      - 3000:3000

  mongo-express:
    container_name: sciapi_mongo_express
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: db
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    links:
      - db

  db:
    image: mongo
    container_name: sciapi_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"