version: '3.7'
services:
  app:
    build:
      context: .
    # command: make db run-debug
    volumes:
      - .:/app
      - /app/node_modules
    # depends_on:
    #   - db
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
#   db:
#     image: mongo:latest
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: rootpassword
#     ports:
#       - 27017:27017
#     volumes:
#       - mongodb_data_container:/data/db

# volumes:
#   mongodb_data_container: